apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  URL_CLOUD_IMAGE: {{ .Values.app.urlCloudImage | b64enc | quote }}
  SECRET: {{ .Values.app.secret | b64enc | quote }}
  BLOG_BASE_URL: {{ .Values.app.blogBaseUrl | b64enc | quote }}
  BLOG_API_KEY: {{ .Values.app.blogApiKey | b64enc | quote }}
