apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  DATABASE_HOST: {{ .Values.database.host | b64enc | quote }}
  DATABASE_PORT: {{ .Values.database.port | b64enc | quote }}
  DATABASE_NAME: {{ .Values.database.name | b64enc | quote }}
  DATABASE_USER: {{ .Values.database.user | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
