apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: {{ template "chart.fullname" . }}-ingress
    annotations:
      kubernetes.io/tls-acme: "true"
      kubernetes.io/ingress.class: "nginx"
      # ingress.kubernetes.io/rewrite-target: /
spec:
    tls:
    - hosts:
      - {{ required "Value domain is not set!" .Values.domain }}
      secretName: {{ template "chart.fullname" . }}-tls
    rules:
      - host: {{ required "Value domain is not set!" .Values.domain }}
        http:
          paths:
            - backend:
                serviceName: {{ template "chart.fullname" . }}-service
                servicePort: 8080
              path: /
